src/Entity/Artiste.php
<?php

namespace App\Entity;

use App\Repository\ArtisteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArtisteRepository::class)]
class Artiste
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Nom obligatoire")]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message:"Description obligatoire, même courte")]
    #[Assert\Length(
        min: 10,
        minMessage: "Mini {{ limit }} caractères"
    )]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 10)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\Url(
        message:"URL {{ value }} invalide",
        protocols: ['http', 'https', 'ftp'],
        relativeProtocol: true
    )]
    private ?string $site_web = null;

    #[ORM\ManyToOne(inversedBy: 'artistes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Style $style = null;

    #[ORM\ManyToOne(inversedBy: 'artistes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Pays $pays = null;

    #[ORM\OneToMany(mappedBy: 'artiste', targetEntity: Concert::class)]
    private Collection $concerts;

    #[ORM\ManyToMany(mappedBy: 'artiste', targetEntity: Album::class)]
    private Collection $albums;

    #[ORM\OneToMany(mappedBy: 'albumArtist', targetEntity: Album::class)]
    private Collection $albumsArtiste;

    public function __construct()
    {
        $this->concerts = new ArrayCollection();
        $this->albums = new ArrayCollection();
        $this->albumsArtiste = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;
        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;
        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;
        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(?string $site_web): static
    {
        $this->site_web = $site_web;
        return $this;
    }

    public function getStyle(): ?Style
    {
        return $this->style;
    }

    public function setStyle(?Style $style): static
    {
        $this->style = $style;
        return $this;
    }

    public function getPays(): ?Pays
    {
        return $this->pays;
    }

    public function setPays(?Pays $pays): static
    {
        $this->pays = $pays;
        return $this;
    }

    /**
     * @return Collection<int, Concert>
     */
    public function getConcerts(): Collection
    {
        return $this->concerts;
    }

    public function addConcert(Concert $concert): static
    {
        if (!$this->concerts->contains($concert)) {
            $this->concerts->add($concert);
            $concert->setArtiste($this);
        }

        return $this;
    }

    public function removeConcert(Concert $concert): static
    {
        if ($this->concerts->removeElement($concert)) {
            // set the owning side to null (unless already changed)
            if ($concert->getArtiste() === $this) {
                $concert->setArtiste(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): static
    {
        if (!$this->albums->contains($album)) {
            $this->albums->add($album);
            $album->addArtiste($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): static
    {
        if ($this->albums->removeElement($album)) {
            $album->removeArtiste($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbumsArtiste(): Collection
    {
        return $this->albumsArtiste;
    }

    public function addAlbumsArtiste(Album $albumsArtiste): static
    {
        if (!$this->albumsArtiste->contains($albumsArtiste)) {
            $this->albumsArtiste->add($albumsArtiste);
            $albumsArtiste->setAlbumArtist($this);
        }

        return $this;
    }

    public function removeAlbumsArtiste(Album $albumsArtiste): static
    {
        if ($this->albumsArtiste->removeElement($albumsArtiste)) {
            // set the owning side to null (unless already changed)
            if ($albumsArtiste->getAlbumArtist() === $this) {
                $albumsArtiste->setAlbumArtist(null);
            }
        }

        return $this;
    }
}

src/Entity/Concert.php
<?php

namespace App\Entity;

use App\Repository\ConcertRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ConcertRepository::class)]
class Concert
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $date_concert = null;

    #[ORM\ManyToOne(inversedBy: 'concerts')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank(message:"Artiste obligatoire")]
    private ?Artiste $artiste = null;

    #[ORM\ManyToOne(inversedBy: 'concerts')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank(message:"Lieu obligatoire")]
    private ?Lieu $lieu = null;

    #[ORM\Column]
    private ?bool $is_festival = null;

    #[ORM\ManyToOne(inversedBy: 'concerts')]
    private ?Festival $Festival = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDateConcert(): ?string
    {
        return $this->date_concert;
    }

    public function setDateConcert(?string $date_concert): static
    {
        $this->date_concert = $date_concert;

        return $this;
    }

    public function getArtiste(): ?Artiste
    {
        return $this->artiste;
    }

    public function setArtiste(?Artiste $artiste): static
    {
        $this->artiste = $artiste;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function isFestival(): ?bool
    {
        return $this->is_festival;
    }

    public function setIsFestival(bool $is_festival): static
    {
        $this->is_festival = $is_festival;

        return $this;
    }

    public function setFestival(?Festival $festival): static
    {
        $this->Festival = $festival;

        return $this;
    }
    public function getFestival(): ?Festival
    {
        return $this->Festival;
    }
}

src/Entity/Festival.php
<?php

namespace App\Entity;

use App\Repository\FestivalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: FestivalRepository::class)]
class Festival
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Nom obligatoire")]
    private ?string $nom_festival = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Url(
        message:"URL {{ value }} invalide",
        protocols: ['http', 'https', 'ftp'],
        relativeProtocol: true
    )]
    private ?string $site_web = null;

    #[ORM\ManyToOne(inversedBy: 'festival')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lieu $lieu = null;

    #[ORM\Column(length: 10, nullable: true)]
    #[Assert\Length(
        max: 10,
        minMessage: "Maxi {{ limit }} caractères"
    )]
    private ?string $date_start = null;

    #[ORM\Column(length: 10, nullable: true)]
    #[Assert\Length(
        max: 10,
        minMessage: "Maxi {{ limit }} caractères"
    )]
    private ?string $date_end = null;

    #[ORM\OneToMany(mappedBy: 'Festival', targetEntity: Concert::class)]
    private Collection $concerts;

    public function __construct()
    {
        $this->concerts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFestival(): ?string
    {
        return $this->nom_festival;
    }

    public function setNomFestival(string $nom_festival): static
    {
        $this->nom_festival = $nom_festival;
        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;
        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(?string $site_web): static
    {
        $this->site_web = $site_web;
        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): static
    {
        $this->lieu = $lieu;
        return $this;
    }

    public function getDateStart(): ?string
    {
        return $this->date_start;
    }

    public function setDateStart(?string $date_start): static
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?string
    {
        return $this->date_end;
    }

    public function setDateEnd(?string $date_end): static
    {
        $this->date_end = $date_end;

        return $this;
    }

    /**
     * @return Collection<int, Concert>
     */
    public function getConcerts(): Collection
    {
        return $this->concerts;
    }

    public function addConcert(Concert $concert): static
    {
        if (!$this->concerts->contains($concert)) {
            $this->concerts->add($concert);
            $concert->setFestival($this);
        }

        return $this;
    }

    public function removeConcert(Concert $concert): static
    {
        if ($this->concerts->removeElement($concert)) {
            // set the owning side to null (unless already changed)
            if ($concert->getFestival() === $this) {
                $concert->setIsFestival(null);
            }
        }

        return $this;
    }
}

src/Controller/ArtisteController.php
<?php

namespace App\Controller;

use App\Entity\Artiste;
use App\Repository\ArtisteRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArtisteController extends AbstractController
{
    #[Route('/artistes', name: 'artistes', methods: ['GET'])]
    public function index(ArtisteRepository $repo, PaginatorInterface $page, Request $request): Response
    {
        //$artistes = $repo->findBy([], ['nom'=>'ASC']);
        $qry_all_artists = $repo->listAllArtists();
        $nbArtists = $repo->countAllArtists();
        $all_artistes = $page->paginate(
            $qry_all_artists,
            $request->query->getInt('page', 1),
            20);
        return $this->render('artiste/listeArtistes.html.twig', [
            'artistes' => $all_artistes,
            'nbArtists' => $nbArtists[0][1]
        ]);
    }

    #[Route('/artiste/{id}', name: 'ficheArtiste', methods: ['GET'])]
    public function ficheArtiste(Artiste $artiste): Response
    {
        return $this->render('artiste/ficheArtiste.html.twig', [
            'artist' => $artiste
        ]);
    }

}

templates/artiste/ficheArtiste.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/flagsMacro.html.twig' as utils %}

{% block title %}{{ parent() }} - Fiche Artiste{% endblock %}

{% block body %}
    {% set nbConcerts = artist.concerts|length %}
    {% set nbAlbums = artist.albumsArtiste|length %}
    {% set flagname = artist.pays.pays|lower %}

    {#{{ dump(artist.concerts) }}#}

    <div class="container">
        <div class="row">
            <div class="col-2 mt-2"><a type="button" class="btn btn-secondary btn-sm" href="{{ path('artistes') }}">Retour</a></div>
            <div class="col-10 my-4 d-flex align-content-flex-start"><h1 class="">{{ artist.nom|upper }}</h1></div>
        </div>


        <div class="card mb-3 col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <div class="row d-flex align-items-start">
            <div class="col-sm-12 col-md-12 col-lg-4 col-xl-4" style="border:1px blue solid;">
                <div id="imgArtistFiche" class="d-flex justify-content-center" style="border:1px red solid; ">
                  <img src="{{ asset('/images/artists/'~artist.image) }}" class="img-fluid" alt="photo {{ artist.nom }}" >
                </div>
            </div>

            <div class="card col-sm-12 col-md-12 col-lg-8 col-xl-8 p-0" style="border:1px solid {{ artist.style.color }};">
              <div class="card-header py-3">
                <div class="card-text d-flex justify-content-center align-items-center gap-5">
                    <span class="badge rounded-pill {% if artist.type == 'Groupe' %} text-danger {% else %} text-warning  {% endif %}">{{ artist.type }}</span>
                    <span class="card-text d-flex align-items-center">
                        {{ utils.flags(artist.pays.pays) }} {{ artist.pays.pays }}
                    </span>
                    <span class="badge rounded-pill bg-info">{{ artist.style.style }}</span>
                    <span class="text-muted"><a href="{{ artist.siteweb }}">Site Web</a></span>
                </div>
              </div>
              <div class="card-body" style="border:1px green solid; height:100%;">
                <div class="card-text">{{ artist.description }}</div>
              </div>
            </div>
          </div>
        </div>
    </div>

    <div class="container mt-5 gap-5 d-flex flex-xl-row flex-lg-row flex-md-row flex-sm-column flex-md-wrap flex-lg-nowrap flex-xl-nowrap">
        <div class="d-flex col-sm-12 col-md-12 col-lg-6 col-xl-6 justify-content-center">
            <div class="card" style="width: 100%;">
              <div class="card-header text-center">
                <h3><img src="{{ asset('/images/icons/mic.svg') }}" class="img-fluid" alt="icone" style="width:20px;"> {% if nbConcerts > 1 %} Concerts {% else %} Concert {% endif %}({{ nbConcerts }})</h3>
              </div>
                <table class="table"><tbody>
                {% for concert in artist.concerts %}
                    <tr class="mt-2">
                        <td>{% if concert.Festival.nomFestival is defined %}
                                {{ concert.Festival.nomFestival }} {{ concert.dateConcert|slice(0,4) }}
                            {% else %}
                                {{ concert.dateConcert|slice(0,4) }}
                            {% endif %}</td>
                        <td>{{ concert.lieu.nom }}</td>
                        <td>{{ concert.lieu.ville }}</td>
                        <td>voir
                            {#<a href="{{ path('ficheConcert', {'id':concert.id}) }}" type="button" class="btn btn-primary btn-sm">
                                <img src="{{ asset('/images/icons/eye.svg') }}" class="img-fluid" alt="icone-voir" width="15" height="15">
                            </a>#}
                        </td>
                    </tr>
                {% endfor %}
                </tbody></table>
            </div>
        </div>

        <div class="d-flex col-sm-12 col-md-12 col-lg-6 col-xl-6 justify-content-center">    
            <div class="card" style="width: 100%;">
              <div class="card-header text-center">
                <h3><img src="{{ asset('/images/icons/boombox.svg') }}" class="img-fluid" alt="icone" style="width:20px;"> {% if nbAlbums > 1 %} Albums {% else %} Album {% endif %} ({{ nbAlbums }})</h3>
              </div>
              <div class="card-body">
                <table class="table">
                  <tbody>
                  {% for album in artist.albumsArtiste %}
                    <tr>
                      <td><img src="{{ asset('/images/albums/'~album.image) }}" alt="pochette album {{ album.nom }}" style="width:80px;"></td>
                      <td>
                          <img src="{{ asset('/images/icons/'~album.albumSupport.support|replace({' ':'', 'é':'e'})|lower~'.png') }}" alt="icon {{ album.albumSupport.support }}" style="width:20px;">
                          {{ album.nom }}
                      </td>
                      <td>{{ album.annee }}</td>
                      <td>
                        <a href="{{ path('ficheAlbum', {'id':album.id}) }}" type="button" class="btn btn-primary btn-sm">
                            <img src="{{ asset('/images/icons/eye.svg') }}" class="img-fluid" alt="icone-voir" width="15" height="15">
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/artiste/listeArtistes.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/flagsMacro.html.twig' as utils %}

{% block title %}{{ parent() }} - Artistes & groupes{% endblock %}

{% block body %}

    <div class="container">
        <h1 class="text-center my-4">Artistes & groupes ({{ nbArtists }})</h1>

        <div class="row">
        {% for artist in artistes %}
            {% set nbConcerts = artist.concerts|length %}
            {% set nbAlbums = artist.albumsArtiste|length %}
            {% set flagname = artist.pays.pays|lower %}

            <div id="card_{{ artist.nom|replace({' ': ''}) }}" class="cardArtist col-sm-12 col-md-6 col-lg-6 col-xl-3 my-2">
                <div class="card mb-2{% if artist.type == 'Groupe' %} border-danger {% else %} border-warning {% endif %}" style="max-width: 30rem;">
                  <div class="card-header d-flex justify-content-between align-items-center {% if artist.type == 'Groupe' %}text-danger{% else %}text-warning{% endif %}">
                      <span class=""><b>{{ artist.nom|upper }}</b></span>
                      <span class=""><small>{{ artist.type }}</small></span>
                  </div>
                   <div class="card-body">
                      <div class="row mb-3 d-flex align-items-start">
                          <div class="col-7 d-flex justify-content-start">
                            <span class="flagname d-flex justify-content-start">
                                {{ utils.flags(artist.pays.pays) }} {{ artist.pays.pays }}
                            </span>
                          </div>
                          <div class="col-5 d-flex justify-content-end">
                              <span class="badge rounded-pill" style="background-color:{{ artist.style.color }}; font-weight:normal;">{{ artist.style.style }}</span>
                          </div>
                      </div>
                      <div id="imgArtistList" class="d-flex align-content-center align-items-center">
                        <img src="{{ asset('/images/artists/'~artist.image) }}" class="card-img-top mx-auto d-block" alt="photo de {{ artist.nom }}">
                      </div>
                      <div class="mt-3 row">
                           <div class="col-7 d-flex justify-content-center">
                               <span class="card-text text-success">{{ nbConcerts }}{% if nbConcerts > 1 %} concerts {% else %} concert{% endif %}</span>
                           </div>
                           <div class="col-5 d-flex justify-content-center">
                               <span class="card-text text-success">{{ nbAlbums }}{% if nbAlbums > 1 %} albums {% else %} album{% endif %}</span>
                           </div>
                       </div>

                  </div>
                  <div class="card-footer d-grid bg-transparent">
                    <a href="{{ path('ficheArtiste', {'id': artist.id}) }}" class="btn border-secondary text-center">En savoir +</a>
                  </div>
                </div>
            </div>
        {% endfor %}
        <div class="navigation d-flex justify-content-center">
            {{ knp_pagination_render(artistes) }}
        </div>

        </div>

        
    </div>
{% endblock %}